apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      function: app
  template:
    metadata:
      labels:
        function: app
    spec:
      containers:
      - name: django
        image: ghcr.io/looklikeamodel/cis-92:milestone-13.2
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: mysite-config
        - secretRef:
            name: mysite-secret
