apiVersion: v1
kind: Pod
metadata:
  name: mysite-pod
  labels:
    function: app
spec:
  containers:
  - name: django
    image: ghcr.io/looklikeamodel/cis-92:milestone-6.2
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    envFrom:
    - configMapRef:
        name: mysite-config
    - secretRef:
        name: mysite-secret